### ISSUE TITLE
About hd630 sleep wake up problem

### ISSUE THREAD

**Issue by zxfccmm4** [danieleongaro/Dell-Optiplex-3050-EFI#1]
Hello, thank you for making this bag for us. I find that I can't wake up and I will die when I sleep. Is there any good solution

**Comment by danieleongaro** [comment]
Hi, I wrote this problem in the "not working" section of the read me. I haven't found a solution yet. This is a common problem for intel HD630. I disabled sleep from the macos settings

**Comment by zxfccmm4** [comment]
Yes, I have disabled sleep now and I am using it well temporarily. Thank you for your reply, and good luck.

**Comment by zxfccmm4** [comment]
Yes, I have disabled sleep now and I am using it well temporarily. Thank you for your reply, and good luck.
